SELECT a.AUTHOR_ID,
       a.AUTHOR_NAME,
       b.CATEGORY,
       SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK_SALES bs JOIN BOOK b ON bs.BOOK_ID = b.BOOK_ID
                   JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY a.AUTHOR_ID, CATEGORY
ORDER BY b.AUTHOR_ID, CATEGORY DESC;
