SELECT DISTINCT os1.USER_ID,
    			os1.PRODUCT_ID
FROM ONLINE_SALE os1 JOIN ONLINE_SALE os2 ON os1.USER_ID = os2.USER_ID
WHERE os1.PRODUCT_ID = os2.PRODUCT_ID
	  AND os1.SALES_DATE < os2.SALES_DATE
ORDER BY os1.USER_ID, os1.PRODUCT_ID DESC;