WITH FISH_INFOS AS (
    SELECT ID,
           FISH_TYPE,
           CASE WHEN LENGTH IS NULL THEN 10
           ELSE LENGTH
           END AS LENGTH_NEW, TIME
    FROM FISH_INFO
)

SELECT 
    ROUND(SUM(LENGTH_NEW) / COUNT(LENGTH_NEW), 2) AS AVERAGE_LENGTH
FROM FISH_INFOS;

# SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AS AVERAGE_LENGTH
# FROM FISH_INFO;
