SELECT c.CAR_ID,
       c.CAR_TYPE,
       ROUND(c.DAILY_FEE * 30 * (1 - p.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('SUV', '세단')
GROUP BY c.CAR_ID, c.CAR_TYPE
HAVING MIN(h.START_DATE) > '2022-11-30' OR MAX(h.END_DATE) < '2022-11-01'
    AND FEE BETWEEN 500000 AND 2000000