SELECT USER_ID,
       NICKNAME,
       CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
       CONCAT(LEFT(TLNO,3), '-', SUBSTR(TLNO,4,4), '-', RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_USER AS ugu JOIN USED_GOODS_BOARD AS ugb ON ugu.USER_ID = ugb.WRITER_ID
GROUP BY USER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY USER_ID DESC;