SELECT YEAR,
       MONTH,
       COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT O.USER_ID)/CUNT_TOT,1) AS PUCHASED_RATIO
FROM (
      SELECT *,
      COUNT(USER_ID) OVER() AS CUNT_TOT
      FROM USER_INFO 
      WHERE YEAR(JOINED)='2021') AS U
      INNER JOIN (
                  SELECT *,
                  YEAR(SALES_DATE) AS YEAR,
                  MONTH(SALES_DATE) AS MONTH
                  FROM ONLINE_SALE) AS O
      ON O.USER_ID = U.USER_ID
GROUP BY 1,2
ORDER BY 1,2;