WITH RECURSIVE OUTS AS (
    SELECT 0 AS N
    UNION ALL
    SELECT N+1
    FROM OUTS
    WHERE N < 23)

SELECT o.N AS HOUR,
       COUNT(ANIMAL_ID) AS COUNT
FROM OUTS o LEFT JOIN ANIMAL_OUTS a ON o.N = HOUR(a.DATETIME)
GROUP BY HOUR
ORDER BY HOUR ASC