SELECT DISTINCT A.ID,
       A.EMAIL,
       A.FIRST_NAME,
       A.LAST_NAME
FROM DEVELOPERS AS A INNER JOIN SKILLCODES AS B ON (A.SKILL_CODE & B.CODE = B.CODE) 
WHERE B.CATEGORY = 'Front End'
ORDER BY A.ID ASC;