SELECT mp.MEMBER_NAME,
       rr.REVIEW_TEXT,
       DATE_FORMAT(rr.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM (
    SELECT MEMBER_ID, COUNT(REVIEW_ID)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 2 DESC
    LIMIT 1
) a
JOIN REST_REVIEW rr ON a.MEMBER_ID = rr.MEMBER_ID
JOIN MEMBER_PROFILE mp ON rr.MEMBER_ID = mp.MEMBER_ID
ORDER BY 3, 2;