WITH MAX_SIZE_PER_YEAR AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    M.YEAR,
    (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN MAX_SIZE_PER_YEAR M 
    ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 
    YEAR ASC, 
    YEAR_DEV ASC;