SELECT distinct cr.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS cr
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS crc ON cr.CAR_ID = crc.CAR_ID
WHERE month(crc.start_date) = 10
AND cr.CAR_TYPE = '세단'
ORDER BY cr.CAR_ID DESC;