SELECT SUM(SCORE) AS SCORE,
       he.EMP_NO,
       EMP_NAME,
       POSITION,
       EMAIL
FROM HR_DEPARTMENT hd
    JOIN HR_EMPLOYEES he ON hd.DEPT_ID = he.DEPT_ID
    JOIN HR_GRADE hg ON he.EMP_NO = hg.EMP_NO
GROUP BY he.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
