WITH avg_length AS (
    SELECT
        FISH_TYPE,
        AVG(IF(LENGTH IS NULL, 10, LENGTH)) AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG_LENGTH >= 33
)

SELECT COUNT(*) AS FISH_COUNT,
       MAX(LENGTH) AS MAX_LENGTH,
       fi.FISH_TYPE
FROM FISH_INFO fi JOIN avg_length al ON fi.FISH_TYPE = al.FISH_TYPE
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE;
